### ISSUE TITLE
ValueChartViewer stylistic adjustments

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#140]
As discussed in meeting on May 31:
- Reduce thickness of weight outlines
- Add black lines between stacked bar segments of group charts
- Scale top right portion to preserve consistency between segment heights

**Comment by aaronpmishkin** [comment]
See experimental branch for implementation of these adjustments.

Commit 805a1be implements scaling the SummaryChart to preserve utility length.

**Comment by aaronpmishkin** [comment]
Commit 7d4e477 completes the stylistic adjustments by adding dividing lines to the stacked bar chart and modifying the width of weight outlines to be one pixel thick.

**Comment by aaronpmishkin** [comment]
The black lines between stacked bar segments are not visible enough. Instead, we will try thicker white bars.

**Comment by aaronpmishkin** [comment]
Merged into main branch by commit 38c8bd3
