### ISSUE TITLE
Implement Refresh Functionality for ValueChartViewer 

### ISSUE THREAD

**Issue by aaronpmishkin** [ValueChart/WebValueCharts#142]
Enable intelligent refreshing for the ValueChartViewer page. The application should reload the ValueChart that was being viewed and display it instead of redirecting to the home page (current functionality).

**Comment by MalakronikMausi** [comment]
If the user is joining the chart, call UpdateObjectiveReferencesService::cleanUpPreferences after the chart is refreshed (this is currently done when "Edit Preferences" is clicked). This will apply necessary changes to the user's preferences if the chart structure has changed.

**Comment by aaronpmishkin** [comment]
Implemented by e6f6a5e
