### ISSUE TITLE
Weight adjustment problem

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#144]
If the weight boundary of 3 objectives overlaps (such that the middle one has a weight of 0), you cannot pull upward to adjust the weights.

This is usually not a big deal, but it becomes a problem when the three boundaries are all at the very bottom. Then, there is no way to adjust these weights - not even by using the pump tool to deflate the other weights.

**Comment by aaronpmishkin** [comment]
Reorder SVG elements to allow users to select the topmost objective in the stack.

**Comment by aaronpmishkin** [comment]
It is possible to adjust the weights if you use the "Resize All" strategy. However, this may not be sufficient in some cases.

**Comment by aaronpmishkin** [comment]
It is also possible adjust the weights using the pump weights tool on the increase setting. Simply click on the objective's text label to increase its weight.

**Comment by aaronpmishkin** [comment]
Using the pump tool to deflate the other weights now works. Implemented by 124f14c94035932dca49a4c9663ad6429da51024.

**Comment by aaronpmishkin** [comment]
I am closing this issue since there are now multiple ways to get around the problem. 

We can revisit it later and attempt to develop better support for 0 weight objectives.
