### ISSUE TITLE
Lock/unlock asynchronous update issue

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#145]
The create workflow now locks charts during editing. This is to prevent joining users from submitting updates to their preferences while the chart is being edited (since these updates will get silently overwritten).

The chart is unlocked when the create component is destroyed (as before). But now, when the creator transitions from the create workflow to ValueChartViewer, the lock button does not reflect the unlocked status. This is probably because it is reading the status before it gets updated - the same probably we had with complete/incomplete in the MyValueCharts page. (But that problem seems to have resolved itself somehow...)

**Comment by aaronpmishkin** [comment]
resolved by 788bd91d7a40f2d6a2aac7e019584c8eed474a88 via caching of ValueChartStatus objects.
