### ISSUE TITLE
Debug and clean up of UpdateObjectiveReferences

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#146]
- Move and rename UpdateObjectiveReferences service
- Test and debug issues with updating references when domain type changes (with and without preserved elements)
- In particular, look at updating alternative references (there are definitely issues here); the order of items in categorical score functions; range that is not a multiple of the interval
- Add immutable ID field to Objectives so that names can be changed without issue - use ID as key throughout

**Comment by MalakronikMausi** [comment]
Validation fails if max outcome selected and range is not multiple of interval. Should disallow ranges that are not multiples of intervals.

**Comment by aaronpmishkin** [comment]
Not that UpdateObjectiveReferencesService has been renamed UpdateValueChartService.

**Comment by MalakronikMausi** [comment]
Everything done except last bullet (will make separate issue for this).
