### ISSUE TITLE
Add immutable ID field to Objectives so that names can be changed

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#155]

**Comment by MalakronikMausi** [comment]
Should be done for Alternatives as well.

**Comment by aaronpmishkin** [comment]
This seems reasonable. To be completed.

**Comment by MalakronikMausi** [comment]
Might consider doing this for Alternatives as well (so that a name change doesn't result in a "new alternative" message).

**Comment by aaronpmishkin** [comment]
Implemented by commit bb7eeb57d6d6cbba87d5a9fe702e716686dc0cda.
