### ISSUE TITLE
Fix Several bugs related to ValueChart Viewer

### ISSUE THREAD

**Issue by aaronpmishkin** [ValueChart/WebValueCharts#160]
- Look into issues with button displays when refreshing ValueCharts.
- The invalid status of the current user is not properly updated when viewing a ValueChart.

**Comment by MalakronikMausi** [comment]
Lag when toggling between chart types.

**Comment by aaronpmishkin** [comment]
The first issue has been resolved by commit 9bd854f1d5becfb52c544df8d88d44e29281c20b.

**Comment by aaronpmishkin** [comment]
The second issue has been resolved by a6e5d61eb92fd79ede9e4ff131c472bec83cc170.

**Comment by aaronpmishkin** [comment]
I have not noticed the severe lag that was experienced when this issue was opened. It is possible that recent changes resolved the issue. 

I am going to close this issue; I will continue to monitor the performance of the ValueChartValueChart and will reopen this if it becomes unacceptable.
