### ISSUE TITLE
Redesign Auto-Save in Create Workflow

### ISSUE THREAD

**Issue by aaronpmishkin** [ValueChart/WebValueCharts#161]

**Comment by MalakronikMausi** [comment]
Only save when changes have been made.
Fail with toastr message if name not available.

**Comment by aaronpmishkin** [comment]
Partially implemented by 74ab37f08ef9511cdcd33d24a844e82bf129a150 and e2287a5ae6d0f399ce2d8add78d3f523fab30cf3.
