### ISSUE TITLE
Prevent users from saving to individual charts

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#163]
Can happen if chart type is changed while user is trying to join.

**Comment by MalakronikMausi** [comment]
A possible solution (now partly implemented) is to delete all other users through the delete user route when the type is changed, and then update the UserRole in the Host service when the delete notification is received (this should be done regardless of how the user was deleted). This prevents users from rejoining the chart through ValueChartViewer. (If a user was removed from a group chart, they can rejoin by using Join Value Chart. If they were removed from an individual chart, they will not be able to join again.)

The only problem is that the delete user route is blocked when charts are locked (as is the case during editing). Perhaps removing users should still be possible when the chart is locked.

**Comment by MalakronikMausi** [comment]
Solution we decided on - add a new route to set the user list to contain just the current user (and make sure to emit the user deleted event for all other users).

**Comment by aaronpmishkin** [comment]
Specifically, we agreed to add a new route that implements the **put** method for the *ValueChart/users* resource. This route will not be restricted by the lock status of the ValueChart, unlike the **post** and **delete** methods for *ValueChart/users*.

**Comment by aaronpmishkin** [comment]
To be completed.

**Comment by aaronpmishkin** [comment]
Resolved by commit bb46c61d5bd03f11cf660244493c13534fb4a400.
