### ISSUE TITLE
New status document created every time ValueChart name is changed

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#165]
Should delete old status document or update the existing one. (Why are status documents indexed by fname instead of chartId?)

**Comment by MalakronikMausi** [comment]
On that subject, we should define a status struct somewhere to improve to transparency.

**Comment by aaronpmishkin** [comment]
Resolved by 51e9e82974fd71a80de1ad96328b7e6bc11d9854.
