### ISSUE TITLE
Clean up ValueChartStatuses

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#174]
- Remove fname from ValueChartStatus
- Have OwnedValueCharts and JoinedValueCharts access status docs by chartId
- Rename userChangesPermitted/incomplete to locked/complete (for clarity)
- Clean up current status documents

**Comment by MalakronikMausi** [comment]
On second thought, rename userChangesPermitted/incomplete to lockedByCreator/lockedBySystem (since I now use the incomplete field to lock in the create workflow, see commit 285f109).

**Comment by aaronpmishkin** [comment]
Implemented by da8ddbe.
