### ISSUE TITLE
Change when navigation warnings are shown

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#175]
- Show warning when changes are made via "Edit Preferences" (but NOT "Edit Chart" since autosave will take care of it)
- (For now) Do not show warning when it's a brand new user who hasn't made any changes in the Viewer (we can add this back if I decide to always turn off autosave during preference editing steps)

**Comment by MalakronikMausi** [comment]
ViewGuard covers changes made in viewer and edit workflow.

**Comment by aaronpmishkin** [comment]
Implemented by b6aef1d48029673bcf2489a5bf673acdc18f19d4 and d395d9d14f208de5824bef699a05dd6bb17a436e.
