### ISSUE TITLE
Chart should be removed from Memberships list when deleted

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#176]

**Comment by aaronpmishkin** [comment]
I assume that this refers to the front-end, rather than the database (where there is no memberships list). It's a simple fix to remove it from both lists.

**Comment by MalakronikMausi** [comment]
Yes, the front-end.

**Comment by aaronpmishkin** [comment]
Resolved by 87efa3e8982e7db85fcd3462747ec3f454b3973c
