### ISSUE TITLE
Color assignment bug

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#197]
Two users can get assigned the same color if they both join the chart locally before either submits to the group chart. Furthermore, the user who submits second will have a different order than the rest (because the first submitter will be inserted BENEATH them in their user list).

**Comment by TylerJamesMalloy** [comment]
I also noticed something related to this. I made a chart on one profile and joined it with another without saving it. When viewing the chart on the owner profile the bars were a single colour and clicking 'view individual chart' did not change this.

**Comment by MalakronikMausi** [comment]
Was the owner also a member of the chart?

**Comment by TylerJamesMalloy** [comment]
The owner was listed on the User List, not sure if that is the same thing as being a member internally?
