### ISSUE TITLE
Improve button interface in ValueChartViewer

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#202]
Simplest solution would be to move some of the drop-down buttons into a drop-down menu. However, we should look into web application standards to see if there are better solutions.

**Comment by TylerJamesMalloy** [comment]
Fixed in branch toolbarUpdate 
https://github.com/ValueChart/WebValueCharts/tree/ToolbarUpdate

**Comment by TylerJamesMalloy** [comment]
Resolved in toolbar update #206
