### ISSUE TITLE
Chart import no longer works

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#209]

**Comment by MalakronikMausi** [comment]
Confirmed to be working. However, the dropdown doesn't close after navigation.

**Comment by TylerJamesMalloy** [comment]
I've tried a few different things (ng-click, jquery, different bootstrap menu types) and I can't manage to get this to work, not sure what the issue is. 

I may have to change the uploadValueChart function in the root component to close the menu, but I'm not too familiar with how to do that.
