### ISSUE TITLE
Improve usability of ScoreFunction definition step

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#25]
1. Devise a way to show and navigate through the Objective hierarchy
2. Add a toggle to invert the function
3. Inform users whether they have visited all plots

Add back immutable score functions, and indicate that they are fixed by creator.

**Comment by aaronpmishkin** [comment]
Am I assigned to this for development or design?

I am hesitant to involve myself too heavily in Create, which is not really in my purview.

**Comment by MalakronikMausi** [comment]
Just for design. I will unassign you since it is ultimately my responsibility.

**Comment by MalakronikMausi** [comment]
Current solution replaces dropdown with select list. This eliminates the need for the nasty "next" button. Also, immutable score functions are now shown in grey font with the label "fixed."

For new users or the creator of a new chart, objectives whose plots haven't been visited are highlighted in bold. This information persists between steps but NOT between instances of the create workflow. No bolding for users who are editing the chart or their preferences, as it is assumed they have already inspected all the plots.

Might consider adding indicators for invalid score functions (red text?). I do not plan to show the Objective hierarchy at this time.

**Comment by MalakronikMausi** [comment]
Closing for now. Will create new issue if current design is found lacking.
