### ISSUE TITLE
ScoreFunction update issues

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#36]
1. When a new user joins an existing chart, their ScoreFunction does not immediately appear - creator has to navigate away (e.g. view Average Chart) and come back to see it
2. When a user is removed from chart, their ScoreFunction does not get cleared from the view - creator has to navigate away and come back

**Comment by MalakronikMausi** [comment]
This is becoming more of a nuisance.

**Comment by aaronpmishkin** [comment]
This issue has been resolved. However, it appears that the fix has introduced minor performance issues stemming from Change detection. See issue #108.
