### ISSUE TITLE
Creator should be able to toggle between group chart and individual chart

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#47]

**Comment by MalakronikMausi** [comment]
Also, should we have a "dual view" for individual charts, one for sensitivity analysis and one that reflects the saved version? Consider these in conjunction.

**Comment by MalakronikMausi** [comment]
We decided that all users should have this functionality, not just the creator.

**Comment by aaronpmishkin** [comment]
Waiting on Group/Individual toggle in create workflow.

**Comment by MalakronikMausi** [comment]
Should all users get real-time updates, or just the creator?

**Comment by aaronpmishkin** [comment]
Completed by 1d87a678140136d4ff7b14e1ff33c344697cfb26.
