### ISSUE TITLE
Should be able to view subsets of users in Group ValueChart

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#48]

**Comment by MalakronikMausi** [comment]
Need to consider possibility of having a "working" chart that the creator can interact with (applying filters, adjusting user weights for sensitivity analysis, etc.) and a "permanent" chart that reflects the chart on the database. Need to think about saving mechanism and what to save (probably changes to weights and score functions but not filters.)

Also, need to move "remove user" functionality out of viewer.

**Comment by aaronpmishkin** [comment]
Implemented by commit f1ad921.
