### ISSUE TITLE
Redesign Weights Elicitation

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#71]
Add adjustment widget from main page so that user can refine weights before seeing the Alternative scores (to reduce bias)

**Comment by aaronpmishkin** [comment]
Perhaps this issue should be pushed back out of batch 4. Christian indicated that we should hold off on implementing 2 and part 1 seems like unnecessarily work at the moment.

**Comment by MalakronikMausi** [comment]
I am keeping this issue around in case Compass decides they want it (part 2, that is). I agree about part 1 - it won't be happening any time soon. I'll move it to a separate issue.

**Comment by MalakronikMausi** [comment]
Not happening.
