### ISSUE TITLE
Alternative layout for ValueChartViewer

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#78]
Compass and some members of our group our uncertain about the value of the bottom right quadrant. Need to consider other possible arrangements, such as the one attached here (provided by Christian).
[VC mockup.pdf](https://github.com/ValueChart/WebValueCharts/files/702625/VC.mockup.pdf)

**Comment by aaronpmishkin** [comment]
What is the status of this issue given our conversation with Christian? Are we waiting on the additional VC feedback before proceeding?

**Comment by MalakronikMausi** [comment]
I think we can proceed without additional feedback since we know what the major issues are.

**Comment by aaronpmishkin** [comment]
Implemented in the external branch; awaiting review for before merging into master.

**Comment by MalakronikMausi** [comment]
Decided to merge Reduced View but not the weight distribution plots (for now).
