### ISSUE TITLE
Locked charts should not be automatically unlocked

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#81]
When user locks chart, navigates away, and then views chart again, it gets unlocked. This can lead to unanticipated effects.

**Comment by MalakronikMausi** [comment]
Should move lock/unlock functionality to admin panel.

**Comment by aaronpmishkin** [comment]
## One potential solution to this issue:

Create a new collection in the database for ValueChart Status documents. These would include:

ValueChart document's ID;
Name of the ValueChart;
Description of the ValueChart;
Password for the ValueChart;
Set of users in the ValueChart;
Number of alternatives in the ValueChart;
ValueChart Completion Status;
ValueChart Lock Status;

We would then read and write these documents to find out whether or not a ValueChart is locked/unlocked and to obtain ValueChart summaries for the My ValueCharts page.

### The drawbacks of this approach: 
- Each write to a ValueChart would require reading the corresponding ValueChart Status document before hand.
  - This adds complexity to the server and is slower than the current situation.

## Another Solution:
Directly add a "locked" field to ValueChart documents in the ValueCharts collection.

### The drawbacks of this approach:
- It could be seen as corrupting a ValueChart document (data) with application-specific information (application logic).

**Comment by aaronpmishkin** [comment]
Decision: Create ValueChart Status collection.

**Comment by aaronpmishkin** [comment]
## Final Solution:

Create ValueChart Status documents with the following fields:

Name of the ValueChart;
Formatted name of the ValueChart;
ValueChart database ID;
ValueChart complete status;
ValueChart user changes permitted status;

Including just these fields in the ValueChart status document allows us to encapsulate all of the application logic for the ValueChart without including any of the data. This is important for avoiding consistency problems.

### Summary Objects

ValueChart Summary objects are created by obtaining both the ValueChart document and the ValueChart status document and then combining the appropriate information.
