### ISSUE TITLE
Fix up XML Parser

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#84]
There are a number of changes needed to the XML parser:
1. Should correctly read/write chart description
2. Should write out categorical domain elements explicitly, and read them in as such
3. Should be more robust to missing elements and unanticipated values (e.g. abstract objective with no children, no primitive objectives, duplicate objective names, objective/alternative outcome mismatch, missing domain, non-positive interval)
4. Should round weights to some level of precision and have validator check that sum is approximately 1 within margin of error
5. (Related) Check model class constructors to verify that default values are appropriate.
6. (Related to 3) Consider throwing meaningful exception in IntervalDomain::calculateElements if interval is non-positive to prevent infinite loop

**Comment by MalakronikMausi** [comment]
Update tests accordingly.

**Comment by MalakronikMausi** [comment]
Item 6 has been fixed.

**Comment by aaronpmishkin** [comment]
Why should we round weights? What do we get out of introducing this added complexity?
