### ISSUE TITLE
Update problem when going from Create workflow to MyValueCharts

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#85]
For some reason, the complete/incomplete status of a chart does not get properly updated when you navigate directly from the Create workflow to MyValueCharts. If you go first to Home and then to MyValueCharts, it does update.

**Comment by MalakronikMausi** [comment]
Confirmed that this problem exists when entering MyValueCharts page from other components.

**Comment by MalakronikMausi** [comment]
Verified that this is what is happening:
1. User leaves create workflow by clicking "My ValueCharts"
2. User opts to keep chart
3. Save request sent
4. MyValueCharts loads, get request sent
5. Get request fetches old chart

Maybe the get request is arriving before the chart has been updated on the DB?

**Comment by aaronpmishkin** [comment]
Investigate: Does angular provide a way to wait until other http requests have been resolved?

**Comment by MalakronikMausi** [comment]
I have confirmed that this problem no longer occurs, but it is unclear why. Could it have something to do with the status documents?

**Comment by MalakronikMausi** [comment]
It does relate to the status documents. By the time the charts are fetched by MyValueCharts, the status documents are up-to-date, but the ValueCharts themselves are not. For this reason, the incomplete and userChangesPermitted fields are up-to-date but password and numUser are not (e.g. try changing the password then going straight to MyValueCharts).

Easy solution would be to add all vcSummary fields to the status documents. But I'm not sure if that's airtight or if there is some element of luck involved.

**Comment by MalakronikMausi** [comment]
FYI the status document is NOT up-to-date by the time it is read by ValueChartViewer (which is why the lock/unlock state is wrong). The server writes are the same in both cases, so maybe it has something to do with the relative complexities of the reads?

**Comment by aaronpmishkin** [comment]
Resolved by 788bd91d7a40f2d6a2aac7e019584c8eed474a88 via caching of ValueChartStatus objects.
