### ISSUE TITLE
Solve ScoreFunctionViewer interaction settings

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#92]
See commit https://github.com/ValueChart/WebValueCharts/commit/2c32e39be1197b3ade656006e3b183c175e5b075

**Comment by MalakronikMausi** [comment]
Basically, I had to disable interaction in ScoreFunctionViewer across the board. Perhaps we should keep it this way? It would get around the different scales issue that was brought up in one of our meetings.

**Comment by aaronpmishkin** [comment]
Why was this disabled? A reasonable amount of effort went in to synchronizing changes between the pop-up window for the ScoreFunctionViewer and the main application?

**Comment by aaronpmishkin** [comment]
See commit 4c98021.
