### ISSUE TITLE
Decouple ScoreFunctionDirective/Viewer/Renderers from Users

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#96]
Ideally, these classes should take a list of score functions and their colours. No other information about Users is required.

This is a prerequisite to proper implementation of default/common score functions.

**Comment by aaronpmishkin** [comment]
I am going to bundle this issue into the much larger task of re-evaluating and then rebuilding how **all** of the Renderers receive data from the ValueChart and are called when changes to the ValueChart are detected.
